project:
  type: website

website:
  title: "ISS608-VAA"
  navbar:
    background: "#4682B4"
    left:
    - text: "Hands-on Exercise"
      menu:
        - text: "Hands-on Exercise 1"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on Exercise 1.html"
        - text: "Hands-on Exercise 2"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on Exercise 2.html"
        - text: "Hands-on Exercise 3a"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on Exercise 3a.html"
        - text: "Hands-on Exercise 3b"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on Exercise 3b.html"
        - text: "Hands-on Exercise 4a"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on Exercise 4a.html"
        - text: "Hands-on Exercise 4b"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on Exercise 4b.html"
        - text: "Hands-on Exercise 4c"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on Exercise 4c.html"
        - text: "Hands-on Exercise 4d"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on Exercise 4d.html"
    
    - text: "Take Home Exercise"
      menu:
        - text: "Take Home Exercise 1a"
          href: "Take-home_Ex/Take-home_Ex01/Take Home Exercise 1a.html"
        - text: "Take Home Exercise 1b"
          href: "Take-home_Ex/Take-home_Ex01/Take Home Exercise 1b.html"
        - text: "Take Home Exercise 2"
          href: "Take-home_Ex/Take-home_Ex02/Take Home Exercise 2.html"
        - text: "Take Home Exercise 3"
          href: "Take-home_Ex/Take-home_Ex03/Take Home Exercise 3.html"
    
    - text: "In-Class Exercise"
      menu: 
        - text: "In-Class Exercise 1"
          href: "In-class_Ex/In-class_Ex01/In-class Exercise 1.html"
        
    right: 
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual
